# Preparando o dataframe.

## Setup e Bibliotecas

In [31]:
from google.colab import drive
drive.mount('/content/drive')

Drive already mounted at /content/drive; to attempt to forcibly remount, call drive.mount("/content/drive", force_remount=True).

In [32]:
# Importando as bibliotecas  pandas e os. Se necessário usar o comando %pip para instalar.
import pandas as pd
import os

# Criando uma variável como  caminho dos arquivos.
tudo = '/content/drive/MyDrive/Code/Myrep/Ecommerce/Datasets/'

# Aqui utilizei um loop para buscar cada arquivo dentro da pasta.
arquivos_csv = [arquivo for arquivo in os.listdir(tudo) if arquivo.endswith('.csv')]


# Criando um DataFrame vazio para armazenar todos os dados
all_months_data = pd.DataFrame()

# Iterando sobre os arquivos. Nota: Iteração é o processo, em programação, de repetição de uma ou mais ações.
for file in arquivos_csv:
    df = pd.read_csv(tudo + file) # Lê o arquivo CSV
    all_months_data = pd.concat([all_months_data, df]) #concatena ao DataFrame principal

# Salva todos os dados em um único arquivo CSV
all_months_data.to_csv('/content/drive/MyDrive/Code/Myrep/Ecommerce/Datasets/db.csv', index=False)

# Criando o Dataframe
vendas = './db.csv'
db = pd.read_csv(vendas)

<ipython-input-32-343640dd2946>:17: DtypeWarning: Columns (0,2,3) have mixed types. Specify dtype option on import or set low_memory=False.
  df = pd.read_csv(tudo + file) # Lê o arquivo CSV

### 2º Parte: Limpeza, tratamento e organização dos dados.

In [33]:
# Uma forma eficiente de mostrar os 5 primeiros objetos.
db.head()

,Order ID,Product,Quantity Ordered,Price Each,Order Date,Purchase Address
0,141234,iPhone,1,700,01/22/19 21:25,"944 Walnut St, Boston, MA 02215"
1,141235,Lightning Charging Cable,1,14.95,01/28/19 14:15,"185 Maple St, Portland, OR 97035"
2,141236,Wired Headphones,2,11.99,01/17/19 13:33,"538 Adams St, San Francisco, CA 94016"
3,141237,27in FHD Monitor,1,149.99,2019-05-01 20:33:00,"738 10th St, Los Angeles, CA 90001"
4,141238,Wired Headphones,1,11.99,01/25/19 11:59,"387 10th St, Austin, TX 73301"

In [34]:
# Verificando a quantidade de NaN no dataframa
db.isna().sum().sum()

3270

In [35]:
# Devido aos NaN, não podemos trabalhar os números. O comando .isna e .isnull detecta os errors NaN.
nan_df= db[db.isna().any(axis=1)]

# O comando .dropna(how= 'all') remove todas as linhas que apresenta NaN.
db = db.dropna(how='all')
# Verificando
db.head()

,Order ID,Product,Quantity Ordered,Price Each,Order Date,Purchase Address
0,141234,iPhone,1,700,01/22/19 21:25,"944 Walnut St, Boston, MA 02215"
1,141235,Lightning Charging Cable,1,14.95,01/28/19 14:15,"185 Maple St, Portland, OR 97035"
2,141236,Wired Headphones,2,11.99,01/17/19 13:33,"538 Adams St, San Francisco, CA 94016"
3,141237,27in FHD Monitor,1,149.99,2019-05-01 20:33:00,"738 10th St, Los Angeles, CA 90001"
4,141238,Wired Headphones,1,11.99,01/25/19 11:59,"387 10th St, Austin, TX 73301"

In [36]:
# Verificando o tipo de saída que temos para cada coluna.
db.info()

<class 'pandas.core.frame.DataFrame'>
Index: 186305 entries, 0 to 186849
Data columns (total 6 columns):
 #   Column            Non-Null Count   Dtype
---  ------            --------------   -----
 0   Order ID          186305 non-null  object
 1   Product           186305 non-null  object
 2   Quantity Ordered  186305 non-null  object
 3   Price Each        186305 non-null  object
 4   Order Date        186305 non-null  object
 5   Purchase Address  186305 non-null  object
dtypes: object(6)
memory usage: 9.9+ MB

In [37]:
# Transformando em números via função "to_numeric"  para cada filtro.
db['Order ID'] = pd.to_numeric(db['Order ID'], errors='coerce')
db['Quantity Ordered'] = pd.to_numeric(db['Quantity Ordered'], errors='coerce')
db['Price Each'] = pd.to_numeric(db['Price Each'], errors='coerce')

# Remover linhas que não contêm datas válidas na coluna "Order Date"
db = db[db['Order Date'] != 'Order Date']

# verificando
db.info()

<class 'pandas.core.frame.DataFrame'>
Index: 185950 entries, 0 to 186849
Data columns (total 6 columns):
 #   Column            Non-Null Count   Dtype
---  ------            --------------   -----
 0   Order ID          185950 non-null  float64
 1   Product           185950 non-null  object
 2   Quantity Ordered  185950 non-null  float64
 3   Price Each        185950 non-null  float64
 4   Order Date        185950 non-null  object
 5   Purchase Address  185950 non-null  object
dtypes: float64(3), object(3)
memory usage: 9.9+ MB

In [38]:
# Criando um caminho para salvar o dataframe já tratado.
caminho = '/content/drive/MyDrive/Code/Myrep/Ecommerce/Datasets/db_r.csv' # db_r será o nome do arquivo novo.

# Salve o DataFrame no CSV.
db.to_csv(caminho, index=False)