In [9]:
# Importando bibliotecas necessárias.
import pandas as pd

# Instânciando o caminho dos dados.
dados = r'C:\Users\guilh\OneDrive\Área de Trabalho\Coding\Portif_git\Churn_Clientes\Dados\Customer-Churn.csv'

#Criando o Dataframe
df = pd.read_csv(dados)

# Habilitando a visualização de todas as colunas.
pd.set_option('display.max_columns', 35 )
df

,Maior65Anos,Conjuge,Dependentes,MesesDeContrato,TelefoneFixo,VariasLinhasTelefonicas,ServicoDeInternet,SegurancaOnline,BackupOnline,SeguroNoDispositivo,SuporteTecnico,TVaCabo,StreamingDeFilmes,TipoDeContrato,PagamentoOnline,FormaDePagamento,ContaMensal,Churn
0,0,Sim,Nao,1,Nao,SemServicoTelefonico,DSL,Nao,Sim,Nao,Nao,Nao,Nao,Mensalmente,Sim,ChequeDigital,29.85,Nao
1,0,Nao,Nao,34,Sim,Nao,DSL,Sim,Nao,Sim,Nao,Nao,Nao,UmAno,Nao,ChequePapel,56.95,Nao
2,0,Nao,Nao,2,Sim,Nao,DSL,Sim,Sim,Nao,Nao,Nao,Nao,Mensalmente,Sim,ChequePapel,53.85,Sim
3,0,Nao,Nao,45,Nao,SemServicoTelefonico,DSL,Sim,Nao,Sim,Sim,Nao,Nao,UmAno,Nao,DebitoEmConta,42.30,Nao
4,0,Nao,Nao,2,Sim,Nao,FibraOptica,Nao,Nao,Nao,Nao,Nao,Nao,Mensalmente,Sim,ChequeDigital,70.70,Sim
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
7038,0,Sim,Sim,24,Sim,Sim,DSL,Sim,Nao,Sim,Sim,Sim,Sim,UmAno,Sim,ChequePapel,84.80,Nao
7039,0,Sim,Sim,72,Sim,Sim,FibraOptica,Nao,Sim,Sim,Nao,Sim,Sim,UmAno,Sim,CartaoDeCredito,103.20,Nao
7040,0,Sim,Sim,11,Nao,SemServicoTelefonico,DSL,Sim,Nao,Nao,Nao,Nao,Nao,Mensalmente,Sim,ChequeDigital,29.60,Nao
7041,1,Sim,Nao,4,Sim,Sim,FibraOptica,Nao,Nao,Nao,Nao,Nao,Nao,Mensalmente,Sim,ChequePapel,74.40,Sim
7042,0,Nao,Nao,66,Sim,Nao,FibraOptica,Sim,Nao,Sim,Sim,Sim,Sim,DoisAnos,Sim,DebitoEmConta,105.65,Nao

In [10]:
# Criando um dicionário para transformar variáveis.
sim_e_nao = { 'Sim': 1,
              'Nao': 0,
              'SemServicoDeInternet' : 0}
df_1 = df[['Conjuge','Dependentes','TelefoneFixo','SegurancaOnline','BackupOnline',
         'SeguroNoDispositivo','SuporteTecnico','TVaCabo','StreamingDeFilmes','PagamentoOnline','Churn']].replace(sim_e_nao)

df_1.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 7043 entries, 0 to 7042
Data columns (total 11 columns):
 #   Column               Non-Null Count  Dtype
---  ------               --------------  -----
 0   Conjuge              7043 non-null   int64
 1   Dependentes          7043 non-null   int64
 2   TelefoneFixo         7043 non-null   int64
 3   SegurancaOnline      7043 non-null   int64
 4   BackupOnline         7043 non-null   int64
 5   SeguroNoDispositivo  7043 non-null   int64
 6   SuporteTecnico       7043 non-null   int64
 7   TVaCabo              7043 non-null   int64
 8   StreamingDeFilmes    7043 non-null   int64
 9   PagamentoOnline      7043 non-null   int64
 10  Churn                7043 non-null   int64
dtypes: int64(11)
memory usage: 605.4 KB

In [11]:
# Utilizando get dummies para categorizar as demais variáveis.
df_2 = pd.get_dummies(df.drop(['Conjuge','Dependentes','TelefoneFixo','SegurancaOnline','BackupOnline',
         'SeguroNoDispositivo','SuporteTecnico','TVaCabo','StreamingDeFilmes','PagamentoOnline','Churn'], axis= 1))

# Encontre as colunas booleanas
boolean_columns = df_2.select_dtypes(include=['bool']).columns

# Use df.loc para aplicar a conversão apenas nas colunas booleanas
df_2.loc[:, boolean_columns] = df_2[boolean_columns].astype(int)

# Concatenando os dados categorizados.
df_3 =pd.concat([df_1, df_2], axis= 1)
df_3.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 7043 entries, 0 to 7042
Data columns (total 27 columns):
 #   Column                                        Non-Null Count  Dtype
---  ------                                        --------------  -----
 0   Conjuge                                       7043 non-null   int64
 1   Dependentes                                   7043 non-null   int64
 2   TelefoneFixo                                  7043 non-null   int64
 3   SegurancaOnline                               7043 non-null   int64
 4   BackupOnline                                  7043 non-null   int64
 5   SeguroNoDispositivo                           7043 non-null   int64
 6   SuporteTecnico                                7043 non-null   int64
 7   TVaCabo                                       7043 non-null   int64
 8   StreamingDeFilmes                             7043 non-null   int64
 9   PagamentoOnline                               7043 non-null   int64
 10  Churn                                         7043 non-null   int64
 11  Maior65Anos                                   7043 non-null   int64
 12  MesesDeContrato                               7043 non-null   int64
 13  ContaMensal                                   7043 non-null   float64
 14  VariasLinhasTelefonicas_Nao                   7043 non-null   int32
 15  VariasLinhasTelefonicas_SemServicoTelefonico  7043 non-null   int32
 16  VariasLinhasTelefonicas_Sim                   7043 non-null   int32
 17  ServicoDeInternet_DSL                         7043 non-null   int32
 18  ServicoDeInternet_FibraOptica                 7043 non-null   int32
 19  ServicoDeInternet_Nao                         7043 non-null   int32
 20  TipoDeContrato_DoisAnos                       7043 non-null   int32
 21  TipoDeContrato_Mensalmente                    7043 non-null   int32
 22  TipoDeContrato_UmAno                          7043 non-null   int32
 23  FormaDePagamento_CartaoDeCredito              7043 non-null   int32
 24  FormaDePagamento_ChequeDigital                7043 non-null   int32
 25  FormaDePagamento_ChequePapel                  7043 non-null   int32
 26  FormaDePagamento_DebitoEmConta                7043 non-null   int32
dtypes: float64(1), int32(13), int64(13)
memory usage: 1.1 MB

In [12]:
# Criando um caminho para salvar o dataframe.
salva = r'C:\Users\guilh\OneDrive\Área de Trabalho\Coding\Portif_git\Churn_Clientes\Datasets\db_tratado.csv'

# Salve o DataFrame 
df_3.to_csv(salva, index=False)